import { Karla } from "next/font/google";
import "./globals.css";

const karla = Karla({
  subsets: ['latin'],
  variable: '--font-karla',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={karla.variable}>{children}</body>
    </html>
  );
}
